[package]
name = "webview_gui"
version = "0.1.0"
authors = ["Winsky Wen <winskywenme@gmail.com>"]
readme = "README.md"
license = "MIT"
edition = "2021"

[dependencies]
webview_gui_sys = { path = "webview_sys", version = "0.1.0" }

[workspace]
members = [
  "webview_sys",
  "demo",
]
