[package]
name = "webview_gui_sys"
version = "0.1.0"
authors = ["Winsky Wen <winskywenme@gmail.com>"]
readme = "README.md"
build = "build.rs"
links = "webview"
license = "MIT"
edition = "2021"

[build-dependencies]
cc = "1"
pkg-config = "0.3"