[package]
name = "webview_gui_demo"
version = "0.1.0"
authors = ["Winsky Wen <winskywenme@gmail.com>"]
readme = "README.md"
license = "MIT"
edition = "2021"
publish = false

[dependencies]
webview_gui = { path = "..", version = "0.1.0" }